// Package providers defines the provider-agnostic interfaces for sending and
// receiving emails, along with the shared data types used by all implementations.
package providers

import (
	"context"
	"time"
)

// ParsedEmail holds the result of parsing a raw RFC 2822 email message.
type ParsedEmail struct {
	MessageID    string
	InReplyTo    string
	References   string
	ThreadID     string // X-Thread-ID / X-GM-THRID for Gmail
	From         string // raw header value e.g. "John Doe <john@example.com>"
	FromAddress  string // extracted email address only
	FromName     string // extracted display name
	To           string // raw To header
	ToAddress    string // extracted email address
	Subject      string
	Date         time.Time
	TextBody     string
	HTMLBody     string
	Attachments  []ParsedAttachment
	RawHeaders   string
	UID          uint32 // IMAP UID — used for marking as seen; 0 for non-IMAP
}

// ParsedAttachment holds the decoded binary content of one attachment.
type ParsedAttachment struct {
	Filename    string
	ContentType string
	Data        []byte
	Size        int64
}

// OutboundMessage is the input for the Sender interface.
type OutboundMessage struct {
	From      string // "Display Name <addr@domain>"
	To        string
	Subject   string
	TextBody  string
	HTMLBody  string // optional — sends multipart/alternative when non-empty
	MessageID string // generated by the caller: <uuid@domain>
	InReplyTo string // Message-ID of the email being replied to
	References string // space-separated chain of prior Message-IDs
}

// Sender can transmit outbound emails.
type Sender interface {
	Send(ctx context.Context, msg OutboundMessage) error
	TestConnection(ctx context.Context) error
}

// Receiver can poll and retrieve inbound emails from a mailbox.
type Receiver interface {
	FetchUnread(ctx context.Context) ([]ParsedEmail, error)
	MarkSeen(ctx context.Context, uid uint32) error
	TestConnection(ctx context.Context) error
}
